# Secret: хранение секретов (пароли, ключи и т.д.).
apiVersion: v1
kind: Secret
metadata:
  name: my-web-app-secrets
type: Opaque
data:
  DATABASE_PASSWORD: <base64-encoded-password> # Пример секрета.